---
- hosts: localhost
  tasks:
    - name: Create an empty bucket
      aws_s3:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        bucket: openscap-data
        mode: create
        permission: private